/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.uangel.marshal.avro.test;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Person6 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -810111146559595463L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Person6\",\"namespace\":\"com.uangel.marshal.avro.test\",\"fields\":[{\"name\":\"name1\",\"type\":\"string\"},{\"name\":\"email1\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Person6> ENCODER =
      new BinaryMessageEncoder<Person6>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Person6> DECODER =
      new BinaryMessageDecoder<Person6>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Person6> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Person6> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Person6>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Person6 to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Person6 from a ByteBuffer. */
  public static Person6 fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence name1;
  @Deprecated public java.lang.CharSequence email1;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Person6() {}

  /**
   * All-args constructor.
   * @param name1 The new value for name1
   * @param email1 The new value for email1
   */
  public Person6(java.lang.CharSequence name1, java.lang.CharSequence email1) {
    this.name1 = name1;
    this.email1 = email1;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name1;
    case 1: return email1;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name1 = (java.lang.CharSequence)value$; break;
    case 1: email1 = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name1' field.
   * @return The value of the 'name1' field.
   */
  public java.lang.CharSequence getName1() {
    return name1;
  }

  /**
   * Sets the value of the 'name1' field.
   * @param value the value to set.
   */
  public void setName1(java.lang.CharSequence value) {
    this.name1 = value;
  }

  /**
   * Gets the value of the 'email1' field.
   * @return The value of the 'email1' field.
   */
  public java.lang.CharSequence getEmail1() {
    return email1;
  }

  /**
   * Sets the value of the 'email1' field.
   * @param value the value to set.
   */
  public void setEmail1(java.lang.CharSequence value) {
    this.email1 = value;
  }

  /**
   * Creates a new Person6 RecordBuilder.
   * @return A new Person6 RecordBuilder
   */
  public static com.uangel.marshal.avro.test.Person6.Builder newBuilder() {
    return new com.uangel.marshal.avro.test.Person6.Builder();
  }

  /**
   * Creates a new Person6 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Person6 RecordBuilder
   */
  public static com.uangel.marshal.avro.test.Person6.Builder newBuilder(com.uangel.marshal.avro.test.Person6.Builder other) {
    return new com.uangel.marshal.avro.test.Person6.Builder(other);
  }

  /**
   * Creates a new Person6 RecordBuilder by copying an existing Person6 instance.
   * @param other The existing instance to copy.
   * @return A new Person6 RecordBuilder
   */
  public static com.uangel.marshal.avro.test.Person6.Builder newBuilder(com.uangel.marshal.avro.test.Person6 other) {
    return new com.uangel.marshal.avro.test.Person6.Builder(other);
  }

  /**
   * RecordBuilder for Person6 instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Person6>
    implements org.apache.avro.data.RecordBuilder<Person6> {

    private java.lang.CharSequence name1;
    private java.lang.CharSequence email1;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.uangel.marshal.avro.test.Person6.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name1)) {
        this.name1 = data().deepCopy(fields()[0].schema(), other.name1);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.email1)) {
        this.email1 = data().deepCopy(fields()[1].schema(), other.email1);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Person6 instance
     * @param other The existing instance to copy.
     */
    private Builder(com.uangel.marshal.avro.test.Person6 other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.name1)) {
        this.name1 = data().deepCopy(fields()[0].schema(), other.name1);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.email1)) {
        this.email1 = data().deepCopy(fields()[1].schema(), other.email1);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'name1' field.
      * @return The value.
      */
    public java.lang.CharSequence getName1() {
      return name1;
    }

    /**
      * Sets the value of the 'name1' field.
      * @param value The value of 'name1'.
      * @return This builder.
      */
    public com.uangel.marshal.avro.test.Person6.Builder setName1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name1 = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name1' field has been set.
      * @return True if the 'name1' field has been set, false otherwise.
      */
    public boolean hasName1() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name1' field.
      * @return This builder.
      */
    public com.uangel.marshal.avro.test.Person6.Builder clearName1() {
      name1 = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'email1' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmail1() {
      return email1;
    }

    /**
      * Sets the value of the 'email1' field.
      * @param value The value of 'email1'.
      * @return This builder.
      */
    public com.uangel.marshal.avro.test.Person6.Builder setEmail1(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.email1 = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'email1' field has been set.
      * @return True if the 'email1' field has been set, false otherwise.
      */
    public boolean hasEmail1() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'email1' field.
      * @return This builder.
      */
    public com.uangel.marshal.avro.test.Person6.Builder clearEmail1() {
      email1 = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Person6 build() {
      try {
        Person6 record = new Person6();
        record.name1 = fieldSetFlags()[0] ? this.name1 : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.email1 = fieldSetFlags()[1] ? this.email1 : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Person6>
    WRITER$ = (org.apache.avro.io.DatumWriter<Person6>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Person6>
    READER$ = (org.apache.avro.io.DatumReader<Person6>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
