// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imgTransfer.proto

package com.uangel.marshal.proto.service;

public final class MapTransferService {
  private MapTransferService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_imgtransfer_Parameter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_imgtransfer_Parameter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021imgTransfer.proto\022\013imgtransfer\"<\n\tPara" +
      "meter\022\n\n\002id\030\001 \001(\005\022\021\n\timageName\030\002 \001(\t\022\020\n\010" +
      "imageMap\030\003 \001(\0142K\n\013MapTransfer\022<\n\010transfe" +
      "r\022\026.imgtransfer.Parameter\032\026.imgtransfer." +
      "Parameter\"\000B8\n com.uangel.marshal.proto." +
      "serviceB\022MapTransferServiceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_imgtransfer_Parameter_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_imgtransfer_Parameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_imgtransfer_Parameter_descriptor,
        new java.lang.String[] { "Id", "ImageName", "ImageMap", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
