// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imgTransfer.proto

package com.uangel.marshal.proto.service;

public interface ParameterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:imgtransfer.Parameter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string imageName = 2;</code>
   */
  java.lang.String getImageName();
  /**
   * <code>string imageName = 2;</code>
   */
  com.google.protobuf.ByteString
      getImageNameBytes();

  /**
   * <code>bytes imageMap = 3;</code>
   */
  com.google.protobuf.ByteString getImageMap();
}
