// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imgTransfer.proto

package com.uangel.marshal.proto.service;

/**
 * Protobuf type {@code imgtransfer.Parameter}
 */
public  final class Parameter extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:imgtransfer.Parameter)
    ParameterOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Parameter.newBuilder() to construct.
  private Parameter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Parameter() {
    id_ = 0;
    imageName_ = "";
    imageMap_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Parameter(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            imageName_ = s;
            break;
          }
          case 26: {

            imageMap_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.uangel.marshal.proto.service.MapTransferService.internal_static_imgtransfer_Parameter_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.uangel.marshal.proto.service.MapTransferService.internal_static_imgtransfer_Parameter_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.uangel.marshal.proto.service.Parameter.class, com.uangel.marshal.proto.service.Parameter.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int IMAGENAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object imageName_;
  /**
   * <code>string imageName = 2;</code>
   */
  public java.lang.String getImageName() {
    java.lang.Object ref = imageName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      imageName_ = s;
      return s;
    }
  }
  /**
   * <code>string imageName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getImageNameBytes() {
    java.lang.Object ref = imageName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      imageName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGEMAP_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString imageMap_;
  /**
   * <code>bytes imageMap = 3;</code>
   */
  public com.google.protobuf.ByteString getImageMap() {
    return imageMap_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getImageNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, imageName_);
    }
    if (!imageMap_.isEmpty()) {
      output.writeBytes(3, imageMap_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getImageNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, imageName_);
    }
    if (!imageMap_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, imageMap_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.uangel.marshal.proto.service.Parameter)) {
      return super.equals(obj);
    }
    com.uangel.marshal.proto.service.Parameter other = (com.uangel.marshal.proto.service.Parameter) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getImageName()
        .equals(other.getImageName());
    result = result && getImageMap()
        .equals(other.getImageMap());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + IMAGENAME_FIELD_NUMBER;
    hash = (53 * hash) + getImageName().hashCode();
    hash = (37 * hash) + IMAGEMAP_FIELD_NUMBER;
    hash = (53 * hash) + getImageMap().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.uangel.marshal.proto.service.Parameter parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.uangel.marshal.proto.service.Parameter parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.uangel.marshal.proto.service.Parameter parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.uangel.marshal.proto.service.Parameter parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.uangel.marshal.proto.service.Parameter parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.uangel.marshal.proto.service.Parameter parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.uangel.marshal.proto.service.Parameter parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.uangel.marshal.proto.service.Parameter parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.uangel.marshal.proto.service.Parameter parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.uangel.marshal.proto.service.Parameter parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.uangel.marshal.proto.service.Parameter parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.uangel.marshal.proto.service.Parameter parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.uangel.marshal.proto.service.Parameter prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code imgtransfer.Parameter}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:imgtransfer.Parameter)
      com.uangel.marshal.proto.service.ParameterOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.uangel.marshal.proto.service.MapTransferService.internal_static_imgtransfer_Parameter_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.uangel.marshal.proto.service.MapTransferService.internal_static_imgtransfer_Parameter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.uangel.marshal.proto.service.Parameter.class, com.uangel.marshal.proto.service.Parameter.Builder.class);
    }

    // Construct using com.uangel.marshal.proto.service.Parameter.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0;

      imageName_ = "";

      imageMap_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.uangel.marshal.proto.service.MapTransferService.internal_static_imgtransfer_Parameter_descriptor;
    }

    public com.uangel.marshal.proto.service.Parameter getDefaultInstanceForType() {
      return com.uangel.marshal.proto.service.Parameter.getDefaultInstance();
    }

    public com.uangel.marshal.proto.service.Parameter build() {
      com.uangel.marshal.proto.service.Parameter result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.uangel.marshal.proto.service.Parameter buildPartial() {
      com.uangel.marshal.proto.service.Parameter result = new com.uangel.marshal.proto.service.Parameter(this);
      result.id_ = id_;
      result.imageName_ = imageName_;
      result.imageMap_ = imageMap_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.uangel.marshal.proto.service.Parameter) {
        return mergeFrom((com.uangel.marshal.proto.service.Parameter)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.uangel.marshal.proto.service.Parameter other) {
      if (other == com.uangel.marshal.proto.service.Parameter.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getImageName().isEmpty()) {
        imageName_ = other.imageName_;
        onChanged();
      }
      if (other.getImageMap() != com.google.protobuf.ByteString.EMPTY) {
        setImageMap(other.getImageMap());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.uangel.marshal.proto.service.Parameter parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.uangel.marshal.proto.service.Parameter) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object imageName_ = "";
    /**
     * <code>string imageName = 2;</code>
     */
    public java.lang.String getImageName() {
      java.lang.Object ref = imageName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imageName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string imageName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getImageNameBytes() {
      java.lang.Object ref = imageName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string imageName = 2;</code>
     */
    public Builder setImageName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      imageName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string imageName = 2;</code>
     */
    public Builder clearImageName() {
      
      imageName_ = getDefaultInstance().getImageName();
      onChanged();
      return this;
    }
    /**
     * <code>string imageName = 2;</code>
     */
    public Builder setImageNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      imageName_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString imageMap_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes imageMap = 3;</code>
     */
    public com.google.protobuf.ByteString getImageMap() {
      return imageMap_;
    }
    /**
     * <code>bytes imageMap = 3;</code>
     */
    public Builder setImageMap(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      imageMap_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes imageMap = 3;</code>
     */
    public Builder clearImageMap() {
      
      imageMap_ = getDefaultInstance().getImageMap();
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:imgtransfer.Parameter)
  }

  // @@protoc_insertion_point(class_scope:imgtransfer.Parameter)
  private static final com.uangel.marshal.proto.service.Parameter DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.uangel.marshal.proto.service.Parameter();
  }

  public static com.uangel.marshal.proto.service.Parameter getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Parameter>
      PARSER = new com.google.protobuf.AbstractParser<Parameter>() {
    public Parameter parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Parameter(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Parameter> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Parameter> getParserForType() {
    return PARSER;
  }

  public com.uangel.marshal.proto.service.Parameter getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

